### ISSUE TITLE
Spell checker

### ISSUE THREAD

**Issue by davidjpeacock** [davidjpeacock/shelbot#16]
20:46 < wikigazer> wait, shelbot spell mispellink

**Comment by alsm** [comment]
So I've ut in a first pass at a spellcheck, not always amazing, depends on the input you give it as dictionary I guess. It assumes the dictionary has one word per line in the file and nothing else. Add your favourite dictionary.

**Comment by davidjpeacock** [comment]
Thanks @alsm 👍

**Comment by davidjpeacock** [comment]
Hey @alsm -

I've done some searching, but I don't really know where to start looking for a dictionary here; can you fire me a link to the one you used on your dev env?

We should probably start putting effort into docs for these third-party-reliant commands.  I'll write up for the GeoIP stuff.  I'll raise a docs epic then put in a bunch of issues.

...as an aside, what's the best way for me to communicate with you when you're off IRC?

Cheers!

David
