### ISSUE TITLE
Wikipedia article puller

### ISSUE THREAD

**Issue by davidjpeacock** [davidjpeacock/shelbot#17]
20:50 < wikigazer> shelbot wikipedia Stanisława Leszczyńska

**Comment by davidjpeacock** [comment]
https://en.wikipedia.org/w/api.php?format=json&action=query&prop=extracts&exintro=&explaintext=&titles=Stanis%C5%82awa%20Leszczy%C5%84ska

Using this query we can pull back article summaries in JSON

**Comment by davidjpeacock** [comment]
21:04 < wikigazer> what could be kewl is to pull that short text and a URL to the full article (if someone wanted to click through to wikipedia)

**Comment by davidjpeacock** [comment]
Fantastic work @alsm!  Nice.

Areas for improvement:

1. Lots of articles have super long excerpts which cause the bot to be disconnected due to channel flooding by the server.

2. Spaces need to be handled; I can call up `cobourg,%20ontario` but not `cobourg, ontario`.

**Comment by davidjpeacock** [comment]
We can likely close this out now; further tweaks and refactors can be new issues?  I'll leave it up to you.

**Comment by alsm** [comment]
Yeah, I think we should close this and raise specific items for any tweak/improvements
