### ISSUE TITLE
Throttle karma requests

### ISSUE THREAD

**Issue by davidjpeacock** [davidjpeacock/shelbot#18]
We need to prevent high-frequency botwars of attrition

**Comment by davidjpeacock** [comment]
Someone went nuts in the channel tonight; getting Donald.Trump to -666 (LOL).

This throttle comes not a moment too soon.

Please clarify, if I'm reading the code correctly it only throttles per user?  That would be my desired operation.  I.e. A single user cannot do multiple consecutive karma for a given string, but others can so if one person gets a flood of praise they don't lose out.

Right?

**Comment by davidjpeacock** [comment]
Answered my own question by re-reading the code and testing; yes it has the desired function of throttling per user.

Suggest we close this and revisit with a new issue if we need to adjust the throttle.

**Comment by davidjpeacock** [comment]
Actually there is a bug.

Repro:
Try foo++ then bar++.

Expected result:  Both update.

Actual result: bar gets ignored since the user previously incremented on foo within timelimit.

**Comment by alsm** [comment]
That was intentional for me, didn't want someone spamming random crap into the karma db either. I'd suggest we close this one, as technically we've done it, and open another if you want to change the way it works

**Comment by davidjpeacock** [comment]
Ack - happy to go with this.  Thanks
