### ISSUE TITLE
Ensure messages reply to user or channel

### ISSUE THREAD

**Issue by davidjpeacock** [davidjpeacock/shelbot#20]
Currently it's possible to send commands to the bot in a private message, but status gets pumped to channel.  This needs to be corrected.

**Comment by davidjpeacock** [comment]
Going to need some advice on this @alsm, please.

Message types are as follows:

// In channel
IRC: 2017/03/16 14:30:36 :dave!dave@fqdn.net PRIVMSG #shelly :foo++
// In pm
IRC: 2017/03/16 14:32:18 :dave!dave@fqdn.net PRIVMSG sheltest :foo++

Differentiating isn't the concern, but I figure you have some ideas on capturing the sending user in PM in order to reply?

**Comment by alsm** [comment]
This should actually be really simple to change, with the irc library we're using PRIVMSGs get read and are passed back to us as a struct with User, Nick, Channel and Text fields. The Channel field for a PM is the username of the person who PM'd us. Pretty much everywhere where we have `conn.PrivMsg(bot.Channel,..)` change it to `conn.PrivMsg(msg.Channel,...)` and it should do what we want.

**Comment by davidjpeacock** [comment]
Ok - this is where I was getting lost.  Thank you for your awesome lib!

**Comment by davidjpeacock** [comment]
@alsm Fixed this with commit eafd41bde443e0ddd901edc03dc272394c99ee6b
