### ISSUE TITLE
Glitches for weather

### ISSUE THREAD

**Issue by davidjpeacock** [davidjpeacock/shelbot#26]
Hey @alsm  - weather is shaping up nicely - well done! :-)

Changed a couple of things; setup pathing for airports.csv.  It's now expected in ~
Added logging for errors on lookup, and specified apiKey needs to go in flags area (durr, that caught me out)

Found a couple bugs:

1. Crash on no airport code argument i.e. `shelbot weather`
1. Encountered a strange error when I tried St. John's in Newfoundland; possibly due to negative temperatures?

In channel:
```
22:25 <@dave> sheltest weather YYT
22:25 < sheltest> Sorry dave, there was an error looking up the weather for St. John's International Airport
```

In log:
```
IRC: 2017/03/18 22:25:28 :dave!dave@d24-235-228-5.home1.cgocable.net PRIVMSG #shelly :sheltest weather YYT
2017/03/18 22:25:30 json: cannot unmarshal number -2.5 into Go struct field Forecast.offset of type int
```

Finally:

Where did the csv come from, and should we be keeping it in our repo?  Was that an accident?  We likely need a note in the code / docs about how to obtain this instead to avoid copyright issues, and also keep our source repo clean.  I need to do the same with GeoIP database too come to think of it.

Thoughts?

**Comment by alsm** [comment]
The data is from here, but with an added header line and some minor edits so it parses properly in the go csv reader. I did wonder about how to talk about getting hold of the data, and whether to include in our repo or not.

**Comment by alsm** [comment]
Also I've updated my forecastio library to fix the offset issue, rebuild and it should be finel
