### ISSUE TITLE
goroutine for dictionary loading

### ISSUE THREAD

**Issue by davidjpeacock** [davidjpeacock/shelbot#33]
# Problem

On low-performance computers such as the Raspberry Pi 3 shelbot lives on, dictionary loading time is unacceptably slow (> 10 minutes) on startup.  The code has been temporarily disabled.

# Proposed Solution

Re-enable spell function within a goroutine, continue loading the bot as normal whilst the goroutine works in the background.

Notify channel / log when spell command is available.

**Comment by davidjpeacock** [comment]
David fail.  I thought the goroutine was working because of course it did on my dev box, but I failed to test it on my Pi.  On there is has different results:

2017/03/22 08:53:38 Loading karma JSON from disk and populating karmaDB map.
2017/03/22 08:53:38 Loading dictionary data, this may take some time.
IRC: 2017/03/22 08:53:38 Connected to IRC server irc.sackheads.org:6667 93.93.130.246:6667
IRC: 2017/03/22 08:53:42 Ready to Listen
IRC: 2017/03/22 08:53:42 :joshua.sackheads.org NOTICE AUTH :*** Looking up your hostname...
IRC: 2017/03/22 08:53:42 :joshua.sackheads.org NOTICE AUTH :*** Found your hostname, cached
IRC: 2017/03/22 08:53:42 :joshua.sackheads.org NOTICE AUTH :*** Checking Ident
2017/03/22 08:53:59 Loading karma JSON from disk and populating karmaDB map.
2017/03/22 08:53:59 Loading dictionary data, this may take some time.
IRC: 2017/03/22 08:53:59 Connected to IRC server irc.sackheads.org:6667 104.131.117.204:6667
IRC: 2017/03/22 08:54:03 Ready to Listen
IRC: 2017/03/22 08:54:03 :haybaler.sackheads.org NOTICE AUTH :*** Looking up your hostname...
IRC: 2017/03/22 08:54:03 :haybaler.sackheads.org NOTICE AUTH :*** Checking Ident
IRC: 2017/03/22 08:54:03 :haybaler.sackheads.org NOTICE AUTH :*** Found your hostname
2017/03/22 08:54:18 Loading dictionary data, this may take some time.
2017/03/22 08:54:18 Loading karma JSON from disk and populating karmaDB map.
2017/03/22 08:54:40 Loading karma JSON from disk and populating karmaDB map.
2017/03/22 08:54:40 Loading dictionary data, this may take some time.
2017/03/22 08:54:59 Loading karma JSON from disk and populating karmaDB map.
2017/03/22 08:54:59 Loading dictionary data, this may take some time.
IRC: 2017/03/22 08:55:00 Connected to IRC server irc.sackheads.org:6667 93.93.130.246:6667
IRC: 2017/03/22 08:55:04 Ready to Listen
IRC: 2017/03/22 08:55:04 :joshua.sackheads.org NOTICE AUTH :*** Looking up your hostname...
IRC: 2017/03/22 08:55:04 :joshua.sackheads.org NOTICE AUTH :*** Found your hostname, cached
IRC: 2017/03/22 08:55:04 :joshua.sackheads.org NOTICE AUTH :*** Checking Ident
2017/03/22 08:55:18 Loading karma JSON from disk and populating karmaDB map.
2017/03/22 08:55:18 Loading dictionary data, this may take some time.
IRC: 2017/03/22 08:55:18 Connected to IRC server irc.sackheads.org:6667 104.131.117.204:6667
IRC: 2017/03/22 08:55:22 Ready to Listen
IRC: 2017/03/22 08:55:22 :haybaler.sackheads.org NOTICE AUTH :*** Looking up your hostname...
IRC: 2017/03/22 08:55:22 :haybaler.sackheads.org NOTICE AUTH :*** Found your hostname, cached
IRC: 2017/03/22 08:55:22 :haybaler.sackheads.org NOTICE AUTH :*** Checking Ident
2017/03/22 08:55:35 Received SIGTERM, exiting
2017/03/22 08:55:36 Writing karma JSON to file.

Re-opening this, and continuing working on it.

**Comment by davidjpeacock** [comment]
Having done more testing, I think this is simply a memory limitation.

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x24adb6, 0x16)
	/usr/local/go/src/runtime/panic.go:596 +0x70
runtime.sysMap(0x1aca0000, 0x5600000, 0x36ae01, 0x3785a8)
	/usr/local/go/src/runtime/mem_linux.go:227 +0xb0
runtime.(*mheap).sysAlloc(0x36aee8, 0x5600000, 0x1caac)
	/usr/local/go/src/runtime/malloc.go:428 +0x2bc
runtime.(*mheap).grow(0x36aee8, 0x2b00, 0x0)
	/usr/local/go/src/runtime/mheap.go:774 +0x48
runtime.(*mheap).allocSpanLocked(0x36aee8, 0x2b00, 0x117fc)
	/usr/local/go/src/runtime/mheap.go:678 +0x468
runtime.(*mheap).alloc_m(0x36aee8, 0x2b00, 0x0, 0x1, 0x21d44)
	/usr/local/go/src/runtime/mheap.go:562 +0xdc
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:627 +0x3c
runtime.systemstack(0x1065df98)
	/usr/local/go/src/runtime/asm_arm.s:278 +0xa8
runtime.(*mheap).alloc(0x36aee8, 0x2b00, 0x0, 0x50101, 0x36bac0)
	/usr/local/go/src/runtime/mheap.go:628 +0x60
runtime.largeAlloc(0x5600000, 0x76fb0201, 0x5)
	/usr/local/go/src/runtime/malloc.go:795 +0x78
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:690 +0x30
runtime.systemstack(0x1067a6b0)
	/usr/local/go/src/runtime/asm_arm.s:264 +0x80
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1132

goroutine 4 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_arm.s:209 +0x4 fp=0x10ac0e08 sp=0x10ac0e04
runtime.mallocgc(0x5600000, 0x21b320, 0x1, 0x18200)
	/usr/local/go/src/runtime/malloc.go:691 +0x9dc fp=0x10ac0e60 sp=0x10ac0e08
runtime.newarray(0x21b320, 0x80000, 0x0)
	/usr/local/go/src/runtime/malloc.go:821 +0x54 fp=0x10ac0e7c sp=0x10ac0e60
runtime.hashGrow(0x20a410, 0x106121e0)
	/usr/local/go/src/runtime/hashmap.go:880 +0x94 fp=0x10ac0ea0 sp=0x10ac0e7c
runtime.mapassign(0x20a410, 0x106121e0, 0x10ac0f3c, 0x0)
	/usr/local/go/src/runtime/hashmap.go:560 +0x334 fp=0x10ac0ef0 sp=0x10ac0ea0
github.com/sajari/fuzzy.(*Model).createSuggestKeys(0x10696000, 0x10dcc9cc, 0xa)
	/Users/peacock/go/src/github.com/sajari/fuzzy/fuzzy.go:344 +0x1fc fp=0x10ac0f44 sp=0x10ac0ef0
github.com/sajari/fuzzy.(*Model).TrainWord(0x10696000, 0x10dcc9cc, 0xa)
	/Users/peacock/go/src/github.com/sajari/fuzzy/fuzzy.go:308 +0x11c fp=0x10ac0f70 sp=0x10ac0f44
github.com/sajari/fuzzy.(*Model).Train(0x10696000, 0x10adc000, 0x3996e, 0x3996e)
	/Users/peacock/go/src/github.com/sajari/fuzzy/fuzzy.go:273 +0x48 fp=0x10ac0f88 sp=0x10ac0f70
main.main.func1(0x106764d0)
	/Users/peacock/go/src/github.com/davidjpeacock/shelbot/main.go:82 +0x1b8 fp=0x10ac0fe4 sp=0x10ac0f88
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:1017 +0x4 fp=0x10ac0fe4 sp=0x10ac0fe4
created by main.main
	/Users/peacock/go/src/github.com/davidjpeacock/shelbot/main.go:83 +0x3e8

goroutine 1 [chan receive]:
main.main()
	/Users/peacock/go/src/github.com/davidjpeacock/shelbot/main.go:126 +0x7bc

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x154
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x30

goroutine 49 [IO wait]:
net.runtime_pollWait(0x76e12f60, 0x72, 0x113ca000)
	/usr/local/go/src/runtime/netpoll.go:164 +0x44
net.(*pollDesc).wait(0x10d4047c, 0x72, 0x341280, 0x340068)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x28
net.(*pollDesc).waitRead(0x10d4047c, 0x113ca000, 0x1000)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x24
net.(*netFD).Read(0x10d40440, 0x113ca000, 0x1000, 0x1000, 0x0, 0x341280, 0x340068)
	/usr/local/go/src/net/fd_unix.go:250 +0x148
net.(*conn).Read(0x106760c8, 0x113ca000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x58
bufio.(*Reader).fill(0x1067c0c0)
	/usr/local/go/src/bufio/bufio.go:97 +0xf4
bufio.(*Reader).ReadSlice(0x1067c0c0, 0x1c0f0a, 0x117c0, 0x11850, 0x10d400d0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:338 +0x9c
bufio.(*Reader).ReadLine(0x1067c0c0, 0x3686d8, 0x137d60e0, 0x137d6094, 0x1c0f5c, 0x137d6094, 0x137d60e0)
	/usr/local/go/src/bufio/bufio.go:367 +0x24
net/textproto.(*Reader).readLineSlice(0x10d537a4, 0x1c0a40, 0x1c0764, 0x1ff288, 0x10d400c0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x44
net/textproto.(*Reader).ReadLine(0x10d537a4, 0x0, 0x10d400c0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x1c
github.com/davidjpeacock/shelbot/irc.(*Conn).Listen(0x10d40180)
	/Users/peacock/go/src/github.com/davidjpeacock/shelbot/irc/irc.go:116 +0x164
created by main.main
	/Users/peacock/go/src/github.com/davidjpeacock/shelbot/main.go:124 +0x78c

goroutine 37 [chan receive]:
main.main.func2(0x106764b0, 0x106c7578, 0x0)
	/Users/peacock/go/src/github.com/davidjpeacock/shelbot/main.go:107 +0xac
created by main.main
	/Users/peacock/go/src/github.com/davidjpeacock/shelbot/main.go:119 +0x664

goroutine 38 [select, locked to thread]:
runtime.gopark(0x256140, 0x0, 0x2435f0, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:271 +0xfc
runtime.selectgoImpl(0x10623fa0, 0x0, 0xc)
	/usr/local/go/src/runtime/select.go:423 +0x119c
runtime.selectgo(0x10623fa0)
	/usr/local/go/src/runtime/select.go:238 +0x10
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:434 +0x2bc
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:1017 +0x4

**Comment by davidjpeacock** [comment]
@alsm I believe we're at a dead-end for spell as far as my Pi is concerned.  Unless you're heart broken about it, I'd vote spell doesn't make the cut.  I'd rather have shelbot running on my low-powered resilient Pi than keep this feature.

But, this is your project as much as mine and I'm open to discussion.

**Comment by davidjpeacock** [comment]
@alsm Follow-up, I just found this: https://www.wordsapi.com/

Thoughts?

**Comment by alsm** [comment]
No worries, kill it, it was fun to try but seems like a lot of work for a small payoff. How about we do something with wiktionary? it uses the same mediawiki api as wikipedia and would be cool to have dictionary lookups

**Comment by davidjpeacock** [comment]
Sounds good man; I like that we're cut from the same cloth.

I thought about wikitionary too; great minds.

I'll rip out the spell stuff, close out this issue, then open a new one for wikitionary.
