### ISSUE TITLE
Geo IP lookup

### ISSUE THREAD

**Issue by davidjpeacock** [davidjpeacock/shelbot#9]
Enable people to determine IP geo location

**Comment by alsm** [comment]
https://github.com/oschwald/geoip2-golang and grab the maxmind db?

**Comment by alsm** [comment]
Probably also add a google maps link too?

**Comment by davidjpeacock** [comment]
Yes to Google Maps link.

I'm thinking ipinfo.io - they return JSON and it's dead simple:

```
$ curl ipinfo.io/24.235.228.5
{
  "ip": "24.235.228.5",
  "hostname": "d24-235-228-5.home1.cgocable.net",
  "city": "Cobourg",
  "region": "Ontario",
  "country": "CA",
  "loc": "43.9598,-78.1651",
  "org": "AS7992 Cogeco Cable",
  "postal": "K9A"
}
```

**Comment by davidjpeacock** [comment]
Options also include:

https://github.com/syohex/go-ipinfo
https://github.com/revh/ipinfo

Exploring right now.
